name: notes
description: An application to save notes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.7
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0+4

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/pencil.png


flutter_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/icons/notes.png"

